/* GENERATED by scripts/generate-tokens.mjs — do not edit by hand. */

/**
 * The palettes shipped in `styles.css`, beyond the default.
 *
 * Setting `data-palette` to one of these ids — on `<html>`, or on any element
 * — re-points every M3 role beneath it. `ThemeProvider` does it for you.
 */
export const PALETTES = [
  { id: "ocean", label: "Ocean", hue: 250 },
  { id: "forest", label: "Forest", hue: 150 },
  { id: "ember", label: "Ember", hue: 55 },
  { id: "rose", label: "Rose", hue: 15 },
] as const

/** A palette id, or `"baseline"` for the kit's own scheme. */
export type Palette = "baseline" | (typeof PALETTES)[number]["id"]
